feat: Implement infinite scrolling to load posts for Home page
leanhduy/threads-clone pull request #18
Opened 2024-06-07 15:14 UTC by leanhduy

create separate Post component

remove some unused variables, libraries components on ImageUploadButton, Home

update the GraphQL client-side queries for fetching list of posts

update the server side's Nexus schema.js for adding query response type for feedForYou query

Closes P1-57

2024-06-08 10:46 UTC, pybotlad requested changes
There are some changes need to be made:
1. There is duplication code for the simulated logged in user in home page (`useQuery` and `mockLogginUser`). Please update code to pick one and remove the other.
2. The query lacks documentation. Add comment to generate better documentation for the graphql queries and types.

Please address these issues and recommit the changes for next review. Thanks

2024-06-08 10:46 UTC, pybotlad commented on client/src/pages/home.js
> +    const [skip, setSkip] = useState(0)
Provide some comment explaining the purpose of these step. Also organize the code by adding section using better comment convention
// * : For the information
// ? : For code explaining
// ! : For important notes
// TODO: For steps that can't be done now but need to be addressed when certain features is implemented.

2024-06-08 10:46 UTC, pybotlad commented on client/src/pages/home.js
> +    useQuery(GET_USER_BY_ID, {
Why there is no variables that will store the result of this useQuery. Then is this useQuery needed? If not, removed it.

2024-06-08 10:46 UTC, pybotlad commented on client/src/pages/home.js
>      const mockCurrentUser = useContext(UserContext)
Choose only one between fetching the user with id = 1 using `useQuery`, or using the hardcoded `mockCurrentUser`

2024-06-08 10:46 UTC, pybotlad commented on client/src/pages/home.js
> +    useEffect(() => {
Add some explanation what the `useEffect` does, and for the code inside as well.

2024-06-08 10:46 UTC, pybotlad commented on server/src/schema.js
> +const FeedQueryResponse = objectType({
Add documentation comment to the type / query.

2024-06-08 10:46 UTC, pybotlad commented on server/src/schema.js
> +    t.field('feedForYou', {
Add documentation comment

2024-06-08 10:46 UTC, pybotlad commented on server/src/schema.js
> +      type: 'FeedQueryResponse',
Add documentation comment

2024-06-10 08:44 UTC, leanhduy commented on client/src/pages/home.js
> +    const [skip, setSkip] = useState(0)
Comments provided.

2024-06-10 08:59 UTC, leanhduy commented on client/src/pages/home.js
> +    useQuery(GET_USER_BY_ID, {
Remove the reference to the hardcoded user object in `mockData.js` and used the result of the GraphQL query `GET_USER_BY_ID`.
The logged user is still hardcoded (id = 1).

2024-06-10 09:00 UTC, leanhduy commented on client/src/pages/home.js
> +    useEffect(() => {
Top-level explanation is provided for each `useEffect` hook

2024-06-10 09:18 UTC, leanhduy commented on server/src/schema.js
> +    t.field('feedForYou', {
Added code-level comment and graphql-level comment

2024-06-10 09:18 UTC, leanhduy commented on server/src/schema.js
> +      type: 'FeedQueryResponse',
Duplicated. See the previous comment.

2024-06-10 09:24 UTC, pybotlad approved these changes
I'm happy with the changes. 
Go ahead and merge into `main` branch

2024-06-10 09:24 UTC, merged